-- drop table interview.candidate;
-- drop table interview.result;
--
-- create table interview.candidate(
--     id integer not null primary key,
--     gender varchar2 (1),
--     age integer,
--     party varchar2(5)
-- );
--
-- create table interview.result(
--     constituency_id integer,
--     candidate_id integer,
--     votes integer
-- );
--
-- insert into interview.candidate values(1, 'M', 55, 'P1');
-- insert into interview.candidate values(2, 'M', 51, 'P1');
-- insert into interview.candidate values(3, 'F', 49, 'P1');
-- insert into interview.candidate values(4, 'M', 60, 'P2');
-- insert into interview.candidate values(5, 'F', 61, 'P2');
-- insert into interview.candidate values(6, 'F', 48, 'P2');
--
-- insert into interview.result values (1,1,847529);
-- insert into interview.result values (1,4,283409);
-- insert into interview.result values (2,2,293841);
-- insert into interview.result values (2,5,394385);
-- insert into interview.result values (3,3,429084);
-- insert into interview.result values (3,6,303890);
--


select place
